version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: yamadori-mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongoadmin
            MONGO_INITDB_ROOT_PASSWORD: secret
            MONGO_INITDB_DATABASE: yamadb
        ports:
            - 27018:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro